// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: sq_esp32_320_240_tft

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_scWelcome
void ui_scWelcome_screen_init(void);
lv_obj_t * ui_scWelcome;
lv_obj_t * ui_panelTop1;
lv_obj_t * ui_lbwelcome;
lv_obj_t * ui_lbwifiInstr;
lv_obj_t * ui_lbMessage;


// SCREEN: ui_scToday
void ui_scToday_screen_init(void);
lv_obj_t * ui_scToday;
lv_obj_t * ui_hh;
lv_obj_t * ui_mm;
lv_obj_t * ui_mmsymbol;
lv_obj_t * ui_ssymbol;
lv_obj_t * ui_ss;
lv_obj_t * ui_panelTop2;
lv_obj_t * ui_ImgIcon;
lv_obj_t * ui_lbtemp;
lv_obj_t * ui_lbdesc;


// SCREEN: ui_scWeather
void ui_scWeather_screen_init(void);
lv_obj_t * ui_scWeather;
lv_obj_t * ui_panelTop3;
lv_obj_t * ui_cmPanelWeather1;
lv_obj_t * ui_cmPanelWeather2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scWelcome_screen_init();
    ui_scToday_screen_init();
    ui_scWeather_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scWelcome);
}
