// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: sq_esp32_320_240_tft

#ifndef _SQ_ESP32_320_240_TFT_UI_H
#define _SQ_ESP32_320_240_TFT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_scWelcome
void ui_scWelcome_screen_init(void);
extern lv_obj_t * ui_scWelcome;
extern lv_obj_t * ui_panelTop1;
extern lv_obj_t * ui_lbwelcome;
extern lv_obj_t * ui_lbwifiInstr;
extern lv_obj_t * ui_lbMessage;
// SCREEN: ui_scToday
void ui_scToday_screen_init(void);
extern lv_obj_t * ui_scToday;
extern lv_obj_t * ui_hh;
extern lv_obj_t * ui_mm;
extern lv_obj_t * ui_mmsymbol;
extern lv_obj_t * ui_ss;
extern lv_obj_t * ui_panelTop2;
extern lv_obj_t * ui_ImgIcon;
extern lv_obj_t * ui_lbtemp;
extern lv_obj_t * ui_lbdesc;
extern lv_obj_t * ui_sssymbol;
// SCREEN: ui_scWeather
void ui_scWeather_screen_init(void);
extern lv_obj_t * ui_scWeather;
extern lv_obj_t * ui_panelTop3;
extern lv_obj_t * ui_cmPanelWeather1;
extern lv_obj_t * ui_cmPanelWeather2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_png_wifi_dis_png);    // assets/png/wifi_dis.png
LV_IMG_DECLARE(ui_img_png_locate_png);    // assets/png/locate.png
LV_IMG_DECLARE(ui_img_white_wl_13_sm_png);    // assets/white/wl_13_sm.png
LV_IMG_DECLARE(ui_img_white_wl_16_sm_png);    // assets/white/wl_16_sm.png
LV_IMG_DECLARE(ui_img_png_wifi_full_png);    // assets/png/wifi_full.png
LV_IMG_DECLARE(ui_img_white_wl_0_sm_png);    // assets/white/wl_0_sm.png
LV_IMG_DECLARE(ui_img_white_wl_10_sm_png);    // assets/white/wl_10_sm.png
LV_IMG_DECLARE(ui_img_white_wl_11_sm_png);    // assets/white/wl_11_sm.png
LV_IMG_DECLARE(ui_img_white_wl_12_sm_png);    // assets/white/wl_12_sm.png
LV_IMG_DECLARE(ui_img_white_wl_14_sm_png);    // assets/white/wl_14_sm.png
LV_IMG_DECLARE(ui_img_white_wl_15_sm_png);    // assets/white/wl_15_sm.png
LV_IMG_DECLARE(ui_img_white_wl_17_sm_png);    // assets/white/wl_17_sm.png
LV_IMG_DECLARE(ui_img_white_wl_18_sm_png);    // assets/white/wl_18_sm.png
LV_IMG_DECLARE(ui_img_white_wl_19_sm_png);    // assets/white/wl_19_sm.png
LV_IMG_DECLARE(ui_img_white_wl_1_sm_png);    // assets/white/wl_1_sm.png
LV_IMG_DECLARE(ui_img_white_wl_20_sm_png);    // assets/white/wl_20_sm.png
LV_IMG_DECLARE(ui_img_white_wl_21_sm_png);    // assets/white/wl_21_sm.png
LV_IMG_DECLARE(ui_img_white_wl_22_sm_png);    // assets/white/wl_22_sm.png
LV_IMG_DECLARE(ui_img_white_wl_23_sm_png);    // assets/white/wl_23_sm.png
LV_IMG_DECLARE(ui_img_white_wl_24_sm_png);    // assets/white/wl_24_sm.png
LV_IMG_DECLARE(ui_img_white_wl_25_sm_png);    // assets/white/wl_25_sm.png
LV_IMG_DECLARE(ui_img_white_wl_26_sm_png);    // assets/white/wl_26_sm.png
LV_IMG_DECLARE(ui_img_white_wl_27_sm_png);    // assets/white/wl_27_sm.png
LV_IMG_DECLARE(ui_img_white_wl_28_sm_png);    // assets/white/wl_28_sm.png
LV_IMG_DECLARE(ui_img_white_wl_29_sm_png);    // assets/white/wl_29_sm.png
LV_IMG_DECLARE(ui_img_white_wl_2_sm_png);    // assets/white/wl_2_sm.png
LV_IMG_DECLARE(ui_img_white_wl_30_sm_png);    // assets/white/wl_30_sm.png
LV_IMG_DECLARE(ui_img_white_wl_31_sm_png);    // assets/white/wl_31_sm.png
LV_IMG_DECLARE(ui_img_white_wl_32_sm_png);    // assets/white/wl_32_sm.png
LV_IMG_DECLARE(ui_img_white_wl_33_sm_png);    // assets/white/wl_33_sm.png
LV_IMG_DECLARE(ui_img_white_wl_34_sm_png);    // assets/white/wl_34_sm.png
LV_IMG_DECLARE(ui_img_white_wl_35_sm_png);    // assets/white/wl_35_sm.png
LV_IMG_DECLARE(ui_img_white_wl_36_sm_png);    // assets/white/wl_36_sm.png
LV_IMG_DECLARE(ui_img_white_wl_37_sm_png);    // assets/white/wl_37_sm.png
LV_IMG_DECLARE(ui_img_white_wl_38_sm_png);    // assets/white/wl_38_sm.png
LV_IMG_DECLARE(ui_img_white_wl_3_sm_png);    // assets/white/wl_3_sm.png
LV_IMG_DECLARE(ui_img_white_wl_4_sm_png);    // assets/white/wl_4_sm.png
LV_IMG_DECLARE(ui_img_white_wl_5_sm_png);    // assets/white/wl_5_sm.png
LV_IMG_DECLARE(ui_img_white_wl_6_sm_png);    // assets/white/wl_6_sm.png
LV_IMG_DECLARE(ui_img_white_wl_7_sm_png);    // assets/white/wl_7_sm.png
LV_IMG_DECLARE(ui_img_white_wl_8_sm_png);    // assets/white/wl_8_sm.png
LV_IMG_DECLARE(ui_img_white_wl_99_sm_png);    // assets/white/wl_99_sm.png
LV_IMG_DECLARE(ui_img_white_wl_9_sm_png);    // assets/white/wl_9_sm.png


LV_FONT_DECLARE(ui_font_dincoros128);
LV_FONT_DECLARE(ui_font_dincoros64);
LV_FONT_DECLARE(ui_font_syHeiTi16);
LV_FONT_DECLARE(ui_font_syHeiTi28);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
