// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: sq_esp32_320_240_tft

#ifndef _UI_COMP_CMPANELTOP_H
#define _UI_COMP_CMPANELTOP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT cmPanelTop
#define UI_COMP_CMPANELTOP_CMPANELTOP 0
#define UI_COMP_CMPANELTOP_IMGWIFISTATE1 1
#define UI_COMP_CMPANELTOP_IMGLOCATE1 2
#define UI_COMP_CMPANELTOP_LBLOCATECN1 3
#define UI_COMP_CMPANELTOP_LBTODAY1 4
#define _UI_COMP_CMPANELTOP_NUM 5
lv_obj_t * ui_cmPanelTop_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
