// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: sq_esp32_320_240_tft

#ifndef _SQ_ESP32_320_240_TFT_UI_COMP_HOOK_H
#define _SQ_ESP32_320_240_TFT_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_cmPanelTop_create_hook(lv_obj_t * comp);
void ui_comp_cmPanelWeather_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
