// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: sq_esp32_320_240_tft

#ifndef _UI_COMP_CMPANELWEATHER_H
#define _UI_COMP_CMPANELWEATHER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT cmPanelWeather
#define UI_COMP_CMPANELWEATHER_CMPANELWEATHER 0
#define UI_COMP_CMPANELWEATHER_IMGICON 1
#define UI_COMP_CMPANELWEATHER_LBTEMP 2
#define UI_COMP_CMPANELWEATHER_LBDATE 3
#define UI_COMP_CMPANELWEATHER_LBDESC 4
#define _UI_COMP_CMPANELWEATHER_NUM 5
lv_obj_t * ui_cmPanelWeather_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
