// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: sq_esp32_320_240_tft

#include "../ui.h"


// COMPONENT cmPanelTop

lv_obj_t * ui_cmPanelTop_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_cmPanelTop;
    cui_cmPanelTop = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_cmPanelTop, lv_pct(100));
    lv_obj_set_height(cui_cmPanelTop, lv_pct(12));
    lv_obj_set_x(cui_cmPanelTop, 0);
    lv_obj_set_y(cui_cmPanelTop, -102);
    lv_obj_set_align(cui_cmPanelTop, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_cmPanelTop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_imgWifiState1;
    cui_imgWifiState1 = lv_img_create(cui_cmPanelTop);
    lv_img_set_src(cui_imgWifiState1, &ui_img_png_wifi_dis_png);
    lv_obj_set_width(cui_imgWifiState1, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(cui_imgWifiState1, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(cui_imgWifiState1, 140);
    lv_obj_set_y(cui_imgWifiState1, 0);
    lv_obj_set_align(cui_imgWifiState1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_imgWifiState1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_imgWifiState1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(cui_imgWifiState1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_imgWifiState1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_imgLocate1;
    cui_imgLocate1 = lv_img_create(cui_cmPanelTop);
    lv_img_set_src(cui_imgLocate1, &ui_img_png_locate_png);
    lv_obj_set_width(cui_imgLocate1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_imgLocate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_imgLocate1, -145);
    lv_obj_set_y(cui_imgLocate1, 0);
    lv_obj_set_align(cui_imgLocate1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_imgLocate1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_imgLocate1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_lbLocateCN1;
    cui_lbLocateCN1 = lv_label_create(cui_cmPanelTop);
    lv_obj_set_width(cui_lbLocateCN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lbLocateCN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_lbLocateCN1, -115);
    lv_obj_set_y(cui_lbLocateCN1, 0);
    lv_obj_set_align(cui_lbLocateCN1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_lbLocateCN1, "");
    lv_obj_set_style_text_font(cui_lbLocateCN1, &ui_font_syHeiTi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_lbToday1;
    cui_lbToday1 = lv_label_create(cui_cmPanelTop);
    lv_obj_set_width(cui_lbToday1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lbToday1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_lbToday1, 18);
    lv_obj_set_y(cui_lbToday1, 0);
    lv_obj_set_align(cui_lbToday1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_lbToday1, "2024年1月1日  星期一");
    lv_obj_set_style_text_font(cui_lbToday1, &ui_font_syHeiTi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CMPANELTOP_NUM);
    children[UI_COMP_CMPANELTOP_CMPANELTOP] = cui_cmPanelTop;
    children[UI_COMP_CMPANELTOP_IMGWIFISTATE1] = cui_imgWifiState1;
    children[UI_COMP_CMPANELTOP_IMGLOCATE1] = cui_imgLocate1;
    children[UI_COMP_CMPANELTOP_LBLOCATECN1] = cui_lbLocateCN1;
    children[UI_COMP_CMPANELTOP_LBTODAY1] = cui_lbToday1;
    lv_obj_add_event_cb(cui_cmPanelTop, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_cmPanelTop, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_cmPanelTop_create_hook(cui_cmPanelTop);
    return cui_cmPanelTop;
}

