// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: sq_esp32_320_240_tft

#include "../ui.h"

void ui_scWelcome_screen_init(void)
{
    ui_scWelcome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scWelcome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panelTop1 = ui_cmPanelTop_create(ui_scWelcome);
    lv_obj_set_x(ui_panelTop1, 0);
    lv_obj_set_y(ui_panelTop1, -104);




    ui_lbwelcome = lv_label_create(ui_scWelcome);
    lv_obj_set_width(ui_lbwelcome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbwelcome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbwelcome, 0);
    lv_obj_set_y(ui_lbwelcome, -55);
    lv_obj_set_align(ui_lbwelcome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbwelcome, "欢迎使用鸣蝉电子钟");
    lv_obj_set_style_text_color(ui_lbwelcome, lv_color_hex(0x00CC00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbwelcome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbwelcome, &ui_font_syHeiTi28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbwifiInstr = lv_label_create(ui_scWelcome);
    lv_obj_set_width(ui_lbwifiInstr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbwifiInstr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbwifiInstr, 12);
    lv_obj_set_y(ui_lbwifiInstr, 26);
    lv_obj_set_align(ui_lbwifiInstr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbwifiInstr,
                      "配网说明：\n1、手机链接WIFI：ESP32_XXXXX；\n2、在手机浏览器输入192.168.4.1；\n3、在\"附近的WIFI\"找到你家的WIFI；\n4、输入密码并保存；");
    lv_obj_set_style_text_font(ui_lbwifiInstr, &ui_font_syHeiTi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMessage = lv_label_create(ui_scWelcome);
    lv_obj_set_width(ui_lbMessage, 320);
    lv_obj_set_height(ui_lbMessage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMessage, 0);
    lv_obj_set_y(ui_lbMessage, 97);
    lv_obj_set_align(ui_lbMessage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMessage, "开始配网....");
    lv_obj_set_style_text_color(ui_lbMessage, lv_color_hex(0xFF9000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbMessage, &ui_font_syHeiTi16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
