// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: sq_esp32_320_240_tft

#include "../ui.h"

void ui_scToday_screen_init(void)
{
    ui_scToday = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scToday, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hh = lv_label_create(ui_scToday);
    lv_obj_set_width(ui_hh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hh, -115);
    lv_obj_set_y(ui_hh, -20);
    lv_obj_set_align(ui_hh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hh, "21");
    lv_obj_set_style_text_color(ui_hh, lv_color_hex(0x03406A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hh, &ui_font_dincoros128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mm = lv_label_create(ui_scToday);
    lv_obj_set_width(ui_mm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mm, -12);
    lv_obj_set_y(ui_mm, -20);
    lv_obj_set_align(ui_mm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mm, "21");
    lv_obj_set_style_text_color(ui_mm, lv_color_hex(0x03406A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mm, &ui_font_dincoros128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mmsymbol = lv_label_create(ui_scToday);
    lv_obj_set_width(ui_mmsymbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mmsymbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mmsymbol, -68);
    lv_obj_set_y(ui_mmsymbol, -25);
    lv_obj_set_align(ui_mmsymbol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mmsymbol, ":");
    lv_obj_set_style_text_color(ui_mmsymbol, lv_color_hex(0x03406A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mmsymbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mmsymbol, &ui_font_dincoros128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ss = lv_label_create(ui_scToday);
    lv_obj_set_width(ui_ss, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ss, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ss, 54);
    lv_obj_set_y(ui_ss, -2);
    lv_obj_set_align(ui_ss, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ss, "20");
    lv_obj_set_style_text_color(ui_ss, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ss, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ss, &ui_font_dincoros64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelTop2 = ui_cmPanelTop_create(ui_scToday);
    lv_obj_set_x(ui_panelTop2, 0);
    lv_obj_set_y(ui_panelTop2, -102);




    ui_ImgIcon = lv_img_create(ui_scToday);
    lv_img_set_src(ui_ImgIcon, &ui_img_white_wl_13_sm_png);
    lv_obj_set_width(ui_ImgIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgIcon, -115);
    lv_obj_set_y(ui_ImgIcon, 64);
    lv_obj_set_align(ui_ImgIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbtemp = lv_label_create(ui_scToday);
    lv_obj_set_width(ui_lbtemp, 226);
    lv_obj_set_height(ui_lbtemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbtemp, 38);
    lv_obj_set_y(ui_lbtemp, 48);
    lv_obj_set_align(ui_lbtemp, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lbtemp, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lbtemp, "小雨 15");
    lv_obj_set_style_text_font(ui_lbtemp, &ui_font_syHeiTi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbdesc = lv_label_create(ui_scToday);
    lv_obj_set_width(ui_lbdesc, 226);
    lv_obj_set_height(ui_lbdesc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbdesc, 38);
    lv_obj_set_y(ui_lbdesc, 86);
    lv_obj_set_align(ui_lbdesc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbdesc, "西北风 ");
    lv_obj_set_style_text_font(ui_lbdesc, &ui_font_syHeiTi16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
